apiVersion: apps/v1
kind: Deployment
metadata:
  name: warning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warning
  template:
    metadata:
      labels:
        app: warning
    spec:
      containers:
        - name: warning
          image: milanbhatiya59/agrisolution-warning:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: warning
spec:
  selector:
    app: warning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
