apiVersion: apps/v1
kind: Deployment
metadata:
  name: soilcard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soilcard
  template:
    metadata:
      labels:
        app: soilcard
    spec:
      containers:
        - name: soilcard
          image: milanbhatiya59/agrisolution-soilcard:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: soilcard
spec:
  selector:
    app: soilcard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
