FROM node:20 as build

WORKDIR /app

COPY ./core/frontend/package*.json ./

RUN npm ci

COPY ./core/frontend ./

RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

COPY ../nginx.frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
