FROM node:18-alpine

WORKDIR /app

COPY ../core/backend/package*.json ./
COPY ../core/backend/constants.js ./
COPY ../core/backend/db ./db
COPY ../core/backend/middlewares ./middlewares
COPY ../core/backend/models ./models
COPY ../core/backend/prompts ./prompts
COPY ../core/backend/utils ./utils
COPY ../core/backend/services/gemini.service.js ./services/
COPY ../core/backend/services/user ./services/user

RUN npm install


EXPOSE 80

CMD ["node", "./services/user/index.js"]