FROM node:18-alpine

WORKDIR /app

COPY ../core/backend/package*.json ./
COPY ../core/backend/constants.js ./
COPY ../core/backend/db ./db
COPY ../core/backend/middlewares ./middlewares
COPY ../core/backend/models ./models
COPY ../core/backend/utils ./utils
COPY ../core/backend/services/gemini.service.js ./services/
COPY ../core/backend/services/warning ./services/warning

RUN npm install


EXPOSE 80

CMD ["node", "./services/warning/index.js"]